version: "3"
services: 
  cli:
    build:
      context: .
    restart: always
    container_name: pastebin-cli
    volumes:
      - ./.env:/opt/app/.env
    ports:
      - 3000:3000
    networks:
      - myNetwork

networks:
  myNetwork:
    driver: bridge